### ISSUE TITLE
Can't save changes

### ISSUE THREAD

**Issue by hazelnot** [tralph3/Steam-Metadata-Editor#10]
I can't seem to save any changes, no matter what I do the modified field stays as "false" and when I restart Steam nothing changes.

**Comment by hazelnot** [comment]
I closed it and tried to open it up again, but now it won't launch at all.

```
Traceback (most recent call last):
  File "/usr/bin/steammetadataeditor", line 1562, in <module>
    mainWindow = MainWindow(silent=args.silent, export=args.export)
  File "/usr/bin/steammetadataeditor", line 104, in __init__
    self.create_main_window()
  File "/usr/bin/steammetadataeditor", line 125, in create_main_window
    self.appInfoVdf = VDF()
  File "/usr/bin/steammetadataeditor", line 1159, in __init__
    self.parsedAppInfo = self.read_all_apps()
  File "/usr/bin/steammetadataeditor", line 1252, in read_all_apps
    app['sections'] = self.parse_subsections()
  File "/usr/bin/steammetadataeditor", line 1199, in parse_subsections
    value = value_parsers[value_type]()
  File "/usr/bin/steammetadataeditor", line 1199, in parse_subsections
    value = value_parsers[value_type]()
  File "/usr/bin/steammetadataeditor", line 1199, in parse_subsections
    value = value_parsers[value_type]()
KeyError: 98
```

**Comment by tralph3** [comment]
Go to your steam installation folder (should be `~/.local/share/steam/`). Look for the `appcache` folder, and delete the `appinfo.vdf` file inside. Try again and tell me what happens.

**Comment by hazelnot** [comment]
It now tells me "Steam couldn't be located in your system, please point to it's[sic] installation directory." I restarted Steam to try to regenerate the file, it kept saying Steam couldn't be located, and when I manually selected the path I got this:
```

Traceback (most recent call last):
  File "/usr/bin/steammetadataeditor", line 1553, in <module>
    STEAM_PATH = get_steam_path()
  File "/usr/bin/steammetadataeditor", line 1533, in get_steam_path
    config.add_section('STEAMPATH')
  File "/usr/lib/python3.9/configparser.py", line 1211, in add_section
    super().add_section(section)
  File "/usr/lib/python3.9/configparser.py", line 659, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'STEAMPATH' already exists
```

**Comment by tralph3** [comment]
Well, to properly debug this I'd need you to send me your `appinfo.vdf` file along with your modifications, located in `.local/share/Steam-Metadata-Editor/config/modifications.json`

**Comment by hazelnot** [comment]
Here they are. I had to put the .vdf in a .zip and rename the .json  to .txt so GitHub would let me upload them.

[appinfo.vdf.zip](https://github.com/tralph3/Steam-Metadata-Editor/files/7273430/appinfo.vdf.zip)
[modifications.json.txt](https://github.com/tralph3/Steam-Metadata-Editor/files/7273431/modifications.json.txt)

**Comment by tralph3** [comment]
Ok I finally got around to taking a look at this, but nothing seems to be out of the ordinary. I took your modifications and your appinfo file and I can see your modifications on the program, the games are being marked as modified correctly, and Steam doesn't revert the changes (do note that I don't own any of the games you modified, but I did a modification for another game and it wasn't rejected). So, I don't really know what to say, nothing seems broken on my end.

Have you tried again in these days? Did you get it to work?

**Comment by hazelnot** [comment]
I tried it again, now it works. No idea why. Maybe a Steam update?

**Comment by pas-de-2** [comment]
Same thing happened to me. Made my first modifications, restarted steam several times and they didn't take. Tried restarting SME, and it kept closing with this error:
```python
Traceback (most recent call last):
  File "C:\Users\xx\Downloads\Steam-Metadata-Editor-master\src\steammetadataedi
tor.py", line 1557, in <module>
    mainWindow = MainWindow(silent=args.silent, export=args.export)
  File "C:\Users\xx\Downloads\Steam-Metadata-Editor-master\src\steammetadataedi
tor.py", line 106, in __init__
    self.appInfoVdf.parsedAppInfo[app]\
KeyError: 2115
```
Deleted `config/modifications.json`, which let me open SME again, made the same changes, and it worked :shrug:

**Comment by tralph3** [comment]
If you get a key error, it *usually* means there's something screwed up in the appinfo file. Deleting it and letting Steam regenerate it usually fixes it.
