### ISSUE TITLE
Error if you scroll on empty part of the GUI after closing "edit launch" window

### ISSUE THREAD

**Issue by mirh** [tralph3/Steam-Metadata-Editor#23]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "src\steammetadataeditor", line 1409, in scroll_canvas
    self.canvas.yview_scroll(direction, "units")
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1994, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel.!scrollableframe.!canvas"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "src\steammetadataeditor", line 1409, in scroll_canvas
    self.canvas.yview_scroll(direction, "units")
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 1994, in yview_scroll
    self.tk.call(self._w, 'yview', 'scroll', number, what)
_tkinter.TclError: invalid command name ".!toplevel.!scrollableframe.!canvas"
```

**Comment by tralph3** [comment]
I am aware of this. I briefly tried to solve it, and it's unreasonably difficult. Or at least, I can't seem to find how to do it, and don't want to spend hours finding how. It's a harmless error. When (if) I make an overhaul of the program, it will go away.
