### ISSUE TITLE
[linux] program crashes immediately after running

### ISSUE THREAD

**Issue by OwOstrich** [tralph3/Steam-Metadata-Editor#41]
```
Traceback (most recent call last):
  File "/opt/sme/main.py", line 45, in <module>
    main()
  File "/opt/sme/main.py", line 34, in main
    mainWindow = MainWindow()
                 ^^^^^^^^^^^^
  File "/opt/sme/gui/main_window.py", line 91, in __init__
    self.create_main_window()
  File "/opt/sme/gui/main_window.py", line 110, in create_main_window
    self.appinfo = Appinfo(self.vdf_path)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 58, in __init__
    self.parsedAppInfo = self.read_all_apps()
                         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 166, in read_all_apps
    app["sections"] = self.parse_subsections()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 99, in parse_subsections
    value = value_parsers[value_type]()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 99, in parse_subsections
    value = value_parsers[value_type]()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 99, in parse_subsections
    value = value_parsers[value_type]()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 4 more times]
  File "/opt/sme/appinfo.py", line 62, in read_string
    string = self.appinfoData[self.offset:strEnd].decode("utf-8")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 12: invalid start byte
```

**Comment by tralph3** [comment]
Please send your `~/.local/share/Steam/appcache/appinfo.vdf` file.

**Comment by OwOstrich** [comment]
here you go:
[https://drive.google.com/file/d/1jgE_3xZ3epnXzNhZ2qgT036hpkDFwxNu/view](https://drive.google.com/file/d/1jgE_3xZ3epnXzNhZ2qgT036hpkDFwxNu)

**Comment by tralph3** [comment]
Please check if the most recent commit fixed your issue.

**Comment by OwOstrich** [comment]
it did indeed, thank you!

**Comment by OwOstrich** [comment]
it did indeed, thank you!
