### ISSUE TITLE
Crashes immediately (Flatpak version)

### ISSUE THREAD

**Issue by atlrvrse** [tralph3/Steam-Metadata-Editor#54]
I recently switched from flatpak steam to the one in arch's package manager, but after i uninstalled flatpak steam it won't run now

> Traceback (most recent call last):
  File "/app/share/Steam-Metadata-Editor/main.py", line 28, in <module>
    from gui.main_window import MainWindow
  File "/app/share/Steam-Metadata-Editor/gui/main_window.py", line 26, in <module>
    from config import config
  File "/app/share/Steam-Metadata-Editor/config.py", line 143, in <module>
    config = Config()
  File "/app/share/Steam-Metadata-Editor/config.py", line 39, in __init__
    self.STEAM_PATH = self.get_steam_path()
  File "/app/share/Steam-Metadata-Editor/config.py", line 132, in get_steam_path
    self.save_steam_path(steam_path)
  File "/app/share/Steam-Metadata-Editor/config.py", line 115, in save_steam_path
    self.config_parser.add_section("STEAMPATH")
  File "/usr/lib/python3.10/configparser.py", line 1213, in add_section
    super().add_section(section)
  File "/usr/lib/python3.10/configparser.py", line 660, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'STEAMPATH' already exists

**Comment by tralph3** [comment]
Go to `~/.local/share/Steam-Metadata-Editor/config` and delete `config.cfg`.

**Comment by atlrvrse** [comment]
thanks
