### ISSUE TITLE
“IndexError: list index out of range” when trying to run in silent mode

### ISSUE THREAD

**Issue by cudail** [tralph3/Steam-Metadata-Editor#57]
Hey! This tool seems really cool. The inconsistencies in game naming on Steam and ALLCAPS™ GAME OF THE YEAR EDITION titles is a constant if mild annoyance.

And it seems to work fine, but I was trying to set up a script and .desktop file to call it in silent mode before starting Steam and discovered that it fails to launch for me in silent mode. I can start `steammetadataeditor` from the command line just fine but `steammetadataeditor -s` or `steammetadataeditor --silent` results in the following error:

```
Traceback (most recent call last):
  File "/opt/sme/main.py", line 46, in <module>
    main()
  File "/opt/sme/main.py", line 35, in main
    main_window = MainWindow()
                  ^^^^^^^^^^^^
  File "/opt/sme/gui/main_window.py", line 66, in __init__
    self.appinfo = Appinfo(
                   ^^^^^^^^
  File "/opt/sme/appinfo.py", line 71, in __init__
    self.parsedAppInfo[app] = self.read_app(app)
                              ^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 180, in read_app
    app["sections"] = self.parse_subsections()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 123, in parse_subsections
    key = self.read_string_appinfo29()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/sme/appinfo.py", line 87, in read_string_appinfo29
    return self.string_pool[index]
           ~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

I am using Manjaro with KDE Plasma desktop 6.1.5 and installed steam-metadata-editor-git via AUR.

**Comment by cudail** [comment]
Ah I just realised that there is already a pull request open to address this https://github.com/tralph3/Steam-Metadata-Editor/pull/55 (and applying the change from it to main_window.py manually myself does seem to solve the error. I will close this issue!
