### ISSUE TITLE
Config files creation problem on start

### ISSUE THREAD

**Issue by tuantran1632001** [tralph3/Steam-Metadata-Editor#9]
Installed through AUR. Start the program from terminal prompt these errors:
```
Traceback (most recent call last):
  File "/usr/bin/steammetadataeditor", line 1553, in <module>
    STEAM_PATH = get_steam_path()
  File "/usr/bin/steammetadataeditor", line 1536, in get_steam_path
    makedirs(CONFIG_PATH)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/tuantran1632001/.local/share/Steam-Metadata-Editor/config'
```

Deleting the folder prompt these errors:
```
Traceback (most recent call last):
  File "/usr/bin/steammetadataeditor", line 1547, in <module>
    with open(f'{CONFIG_PATH}/config.cfg', 'w'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/tuantran1632001/.local/share/Steam-Metadata-Editor/config/config.cfg'
```

**Comment by tralph3** [comment]
Should be fixed now. Thanks for reporting.
